// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: peer.proto

package kibitz

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetInfo struct {
	Addr                 *string  `protobuf:"bytes,1,req,name=addr" json:"addr,omitempty"`
	Natdom               *string  `protobuf:"bytes,2,opt,name=natdom" json:"natdom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfo) Reset()         { *m = NetInfo{} }
func (m *NetInfo) String() string { return proto.CompactTextString(m) }
func (*NetInfo) ProtoMessage()    {}
func (*NetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_d4a20dbc36d3d920, []int{0}
}
func (m *NetInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *NetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfo.Merge(dst, src)
}
func (m *NetInfo) XXX_Size() int {
	return m.Size()
}
func (m *NetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfo proto.InternalMessageInfo

func (m *NetInfo) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *NetInfo) GetNatdom() string {
	if m != nil && m.Natdom != nil {
		return *m.Natdom
	}
	return ""
}

type PeerInfo struct {
	StatusCode  *int32  `protobuf:"varint,1,req,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Subsystem   *string `protobuf:"bytes,2,req,name=subsystem" json:"subsystem,omitempty"`
	Environment *string `protobuf:"bytes,3,opt,name=environment" json:"environment,omitempty"`
	ServerId    *string `protobuf:"bytes,4,req,name=server_id,json=serverId" json:"server_id,omitempty"`
	Hostname    *string `protobuf:"bytes,5,opt,name=hostname" json:"hostname,omitempty"`
	Datacenter  *string `protobuf:"bytes,6,opt,name=datacenter" json:"datacenter,omitempty"`
	Rack        *string `protobuf:"bytes,7,opt,name=rack" json:"rack,omitempty"`
	// lamport clocks (see lamport.go)
	TimeChecked          *uint64    `protobuf:"varint,8,opt,name=time_checked,json=timeChecked" json:"time_checked,omitempty"`
	TimeUp               *uint64    `protobuf:"varint,9,opt,name=time_up,json=timeUp" json:"time_up,omitempty"`
	TimeCreated          *uint64    `protobuf:"varint,10,opt,name=time_created,json=timeCreated" json:"time_created,omitempty"`
	TimeConf             *uint64    `protobuf:"varint,11,opt,name=time_conf,json=timeConf" json:"time_conf,omitempty"`
	Via                  *string    `protobuf:"bytes,17,opt,name=via" json:"via,omitempty"`
	NetInfo              []*NetInfo `protobuf:"bytes,20,rep,name=net_info,json=netInfo" json:"net_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_d4a20dbc36d3d920, []int{1}
}
func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(dst, src)
}
func (m *PeerInfo) XXX_Size() int {
	return m.Size()
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *PeerInfo) GetSubsystem() string {
	if m != nil && m.Subsystem != nil {
		return *m.Subsystem
	}
	return ""
}

func (m *PeerInfo) GetEnvironment() string {
	if m != nil && m.Environment != nil {
		return *m.Environment
	}
	return ""
}

func (m *PeerInfo) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *PeerInfo) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *PeerInfo) GetDatacenter() string {
	if m != nil && m.Datacenter != nil {
		return *m.Datacenter
	}
	return ""
}

func (m *PeerInfo) GetRack() string {
	if m != nil && m.Rack != nil {
		return *m.Rack
	}
	return ""
}

func (m *PeerInfo) GetTimeChecked() uint64 {
	if m != nil && m.TimeChecked != nil {
		return *m.TimeChecked
	}
	return 0
}

func (m *PeerInfo) GetTimeUp() uint64 {
	if m != nil && m.TimeUp != nil {
		return *m.TimeUp
	}
	return 0
}

func (m *PeerInfo) GetTimeCreated() uint64 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *PeerInfo) GetTimeConf() uint64 {
	if m != nil && m.TimeConf != nil {
		return *m.TimeConf
	}
	return 0
}

func (m *PeerInfo) GetVia() string {
	if m != nil && m.Via != nil {
		return *m.Via
	}
	return ""
}

func (m *PeerInfo) GetNetInfo() []*NetInfo {
	if m != nil {
		return m.NetInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*NetInfo)(nil), "kibitz.NetInfo")
	proto.RegisterType((*PeerInfo)(nil), "kibitz.PeerInfo")
}
func (m *NetInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Addr == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Addr)))
		i += copy(dAtA[i:], *m.Addr)
	}
	if m.Natdom != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Natdom)))
		i += copy(dAtA[i:], *m.Natdom)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PeerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PeerInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StatusCode == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPeer(dAtA, i, uint64(*m.StatusCode))
	}
	if m.Subsystem == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Subsystem)))
		i += copy(dAtA[i:], *m.Subsystem)
	}
	if m.Environment != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Environment)))
		i += copy(dAtA[i:], *m.Environment)
	}
	if m.ServerId == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.ServerId)))
		i += copy(dAtA[i:], *m.ServerId)
	}
	if m.Hostname != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Hostname)))
		i += copy(dAtA[i:], *m.Hostname)
	}
	if m.Datacenter != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Datacenter)))
		i += copy(dAtA[i:], *m.Datacenter)
	}
	if m.Rack != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Rack)))
		i += copy(dAtA[i:], *m.Rack)
	}
	if m.TimeChecked != nil {
		dAtA[i] = 0x40
		i++
		i = encodeVarintPeer(dAtA, i, uint64(*m.TimeChecked))
	}
	if m.TimeUp != nil {
		dAtA[i] = 0x48
		i++
		i = encodeVarintPeer(dAtA, i, uint64(*m.TimeUp))
	}
	if m.TimeCreated != nil {
		dAtA[i] = 0x50
		i++
		i = encodeVarintPeer(dAtA, i, uint64(*m.TimeCreated))
	}
	if m.TimeConf != nil {
		dAtA[i] = 0x58
		i++
		i = encodeVarintPeer(dAtA, i, uint64(*m.TimeConf))
	}
	if m.Via != nil {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPeer(dAtA, i, uint64(len(*m.Via)))
		i += copy(dAtA[i:], *m.Via)
	}
	if len(m.NetInfo) > 0 {
		for _, msg := range m.NetInfo {
			dAtA[i] = 0xa2
			i++
			dAtA[i] = 0x1
			i++
			i = encodeVarintPeer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintPeer(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *NetInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Addr != nil {
		l = len(*m.Addr)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.Natdom != nil {
		l = len(*m.Natdom)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PeerInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StatusCode != nil {
		n += 1 + sovPeer(uint64(*m.StatusCode))
	}
	if m.Subsystem != nil {
		l = len(*m.Subsystem)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.Environment != nil {
		l = len(*m.Environment)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.ServerId != nil {
		l = len(*m.ServerId)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.Hostname != nil {
		l = len(*m.Hostname)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.Datacenter != nil {
		l = len(*m.Datacenter)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.Rack != nil {
		l = len(*m.Rack)
		n += 1 + l + sovPeer(uint64(l))
	}
	if m.TimeChecked != nil {
		n += 1 + sovPeer(uint64(*m.TimeChecked))
	}
	if m.TimeUp != nil {
		n += 1 + sovPeer(uint64(*m.TimeUp))
	}
	if m.TimeCreated != nil {
		n += 1 + sovPeer(uint64(*m.TimeCreated))
	}
	if m.TimeConf != nil {
		n += 1 + sovPeer(uint64(*m.TimeConf))
	}
	if m.Via != nil {
		l = len(*m.Via)
		n += 2 + l + sovPeer(uint64(l))
	}
	if len(m.NetInfo) > 0 {
		for _, e := range m.NetInfo {
			l = e.Size()
			n += 2 + l + sovPeer(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPeer(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPeer(x uint64) (n int) {
	return sovPeer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NetInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPeer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Addr = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Natdom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Natdom = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPeer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPeer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PeerInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPeer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PeerInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PeerInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StatusCode = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subsystem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Subsystem = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Environment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Environment = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ServerId = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Hostname = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datacenter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Datacenter = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rack", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Rack = &s
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeChecked", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeChecked = &v
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeUp = &v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeCreated", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeCreated = &v
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeConf", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeConf = &v
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Via", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Via = &s
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPeer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetInfo = append(m.NetInfo, &NetInfo{})
			if err := m.NetInfo[len(m.NetInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPeer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPeer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPeer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPeer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPeer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPeer
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPeer
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPeer(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPeer = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPeer   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("peer.proto", fileDescriptor_peer_d4a20dbc36d3d920) }

var fileDescriptor_peer_d4a20dbc36d3d920 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xd7, 0x71, 0xe2, 0x3f, 0xe3, 0x85, 0xcd, 0x8a, 0x65, 0x2b, 0xda, 0xe2, 0xba, 0x39,
	0x99, 0x1e, 0x72, 0x28, 0xf4, 0x05, 0x9a, 0x53, 0x2e, 0xa5, 0x18, 0x7a, 0x36, 0x8a, 0x35, 0x26,
	0x26, 0x58, 0x32, 0xb2, 0x12, 0x68, 0x1f, 0xa3, 0xa7, 0x3e, 0x52, 0x8f, 0x7d, 0x84, 0x92, 0xbe,
	0x48, 0xf1, 0x28, 0x34, 0xb9, 0x7d, 0xf3, 0xfb, 0xe6, 0x1b, 0x69, 0x18, 0x80, 0x0e, 0xd1, 0xcc,
	0x3b, 0xa3, 0xad, 0x66, 0xc1, 0xa6, 0x59, 0x35, 0xf6, 0x65, 0x76, 0x07, 0xe1, 0x03, 0xda, 0xa5,
	0xaa, 0x35, 0x63, 0x30, 0x16, 0x52, 0x1a, 0xee, 0x65, 0xa3, 0x3c, 0x2e, 0x48, 0xb3, 0xff, 0x10,
	0x28, 0x61, 0xa5, 0x6e, 0xf9, 0x28, 0xf3, 0xf2, 0xb8, 0x38, 0x54, 0xb3, 0x57, 0x1f, 0xa2, 0x47,
	0x44, 0x43, 0xc1, 0x2b, 0x48, 0x7a, 0x2b, 0xec, 0xb6, 0x2f, 0x2b, 0x2d, 0x91, 0xf2, 0x93, 0x02,
	0x1c, 0x5a, 0x68, 0x89, 0xec, 0x12, 0xe2, 0x7e, 0xbb, 0xea, 0x9f, 0x7b, 0x8b, 0xc3, 0xa0, 0x61,
	0xfc, 0x11, 0xb0, 0x0c, 0x12, 0x54, 0xbb, 0xc6, 0x68, 0xd5, 0xa2, 0xb2, 0xdc, 0xa7, 0x87, 0x4e,
	0x11, 0xbb, 0x80, 0xb8, 0x47, 0xb3, 0x43, 0x53, 0x36, 0x92, 0x8f, 0x29, 0x1f, 0x39, 0xb0, 0x94,
	0xec, 0x1c, 0xa2, 0xb5, 0xee, 0xad, 0x12, 0x2d, 0xf2, 0x09, 0x65, 0x7f, 0x6a, 0x96, 0x02, 0x48,
	0x61, 0x45, 0x85, 0xca, 0xa2, 0xe1, 0x01, 0xb9, 0x27, 0x64, 0x58, 0xd9, 0x88, 0x6a, 0xc3, 0x43,
	0x72, 0x48, 0xb3, 0x6b, 0xf8, 0x6d, 0x9b, 0x16, 0xcb, 0x6a, 0x8d, 0xd5, 0x06, 0x25, 0x8f, 0x32,
	0x2f, 0x1f, 0x17, 0xc9, 0xc0, 0x16, 0x0e, 0xb1, 0x33, 0x08, 0xa9, 0x65, 0xdb, 0xf1, 0x98, 0xdc,
	0x60, 0x28, 0x9f, 0xba, 0x63, 0xd6, 0xa0, 0xb0, 0x28, 0x39, 0x9c, 0x64, 0x1d, 0x1a, 0x76, 0x71,
	0x2d, 0x5a, 0xd5, 0x3c, 0x21, 0x3f, 0x22, 0x5f, 0xab, 0x9a, 0x4d, 0xc1, 0xdf, 0x35, 0x82, 0xff,
	0xa5, 0xef, 0x0c, 0x92, 0xdd, 0x40, 0xa4, 0xd0, 0x96, 0x8d, 0xaa, 0x35, 0xff, 0x97, 0xf9, 0x79,
	0x72, 0xfb, 0x67, 0xee, 0x4e, 0x37, 0x3f, 0xdc, 0xad, 0x08, 0x95, 0x13, 0xf7, 0xd3, 0xf7, 0x7d,
	0xea, 0x7d, 0xec, 0x53, 0xef, 0x73, 0x9f, 0x7a, 0x6f, 0x5f, 0xe9, 0xaf, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf6, 0xaa, 0xc3, 0x07, 0xf2, 0x01, 0x00, 0x00,
}
